[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
#default_network = "${SEPOLIA_RPC}"
sepolia = "${SEPOLIA_RPC}"
base-sepolia = "${BASE_SEPOLIA_RPC}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC}"
morph-holesky = "${MORPH_HOLESKY_RPC}"
scroll-sepolia = "${SCROLL_SEPOLIA_RPC}"
linea-sepolia = "${LINNEA_SEPOLIA_RPC}"
zircuit = "${ZIRCUIT_TESTNET_RPC}"
apechain = "${APECHAIN_JENKINS_RPC}"
zero-sepolia = "${ZERO_SEPOLIA_RPC}"

[etherscan]
sepolia = { key = "${SEPOLIA_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
# base-sepolia =
# arbitrum-sepolia =
# scroll-sepolia = 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
